### ISSUE TITLE
Takes ~300ms to run 1 invocation

### ISSUE THREAD

**Issue by rcoh** [assert-rs/assert_cli#100]
- `assert_cli` version: 0.5
- Rust version: 1.25.0
- OS and version: Ubuntu 16.04
Unfortunately, `cargo run` takes at minimum about 300ms on my computer:
```
➜  angle-grinder git:(master) ✗ time cargo run --bin agrind -- '* | json | count' --file test_files/empty
    Finished dev [unoptimized + debuginfo] target(s) in 0.0 secs
     Running `target/debug/agrind '* | json | count' --file test_files/empty`
No data
cargo run --bin agrind -- '* | json | count' --file test_files/empty  0.22s user 0.06s system 92% cpu 0.307 total
```

It makes it impractical to run hundreds of integration tests with assert_cli.

I'm not positive what a better way would be -- I guess running the binary in dist directly if it exists?

**Comment by killercup** [comment]
Hm, indeed. `cargo run` adds ~300ms overhead on my machine as well (on macOS). That's quite unfortunate! Executing the binary directly takes less than 1ms, though, so making sure everything is compiled correctly and then executing with the then-known path should be a good workaround.

We should absolutely add this to the docs. And I'll ask the cargo team if there is a way to use cargo's "find binary" feature without having it check if it needs to compile things (which I guess is what's taking so long -- `--locked --frozen` doesn't speed things up).

**Comment by epage** [comment]
> We should absolutely add this to the docs. And I'll ask the cargo team if there is a way to use cargo's "find binary" feature without having it check if it needs to compile things

Another use case for such a feature is packaging.  Looking into this is coming up on my plate for packaging.

**Comment by killercup** [comment]
cargo issue: https://github.com/rust-lang/cargo/issues/5315

**Comment by epage** [comment]
The responsibility for this is moving to [assert_cmd](https://github.com/assert-rs/assert_cmd) and tis will be addressed in https://github.com/assert-rs/assert_cmd/issues/6

assert_cli is going to morph into a wider-focused tool, including things like assert_fs.  See https://github.com/assert-rs/assert_cli/issues/41
