### ISSUE TITLE
What should the name be for `Assert::example`

### ISSUE THREAD

**Issue by epage** [assert-rs/assert_cli#110]
#108 added `Assert::example`.

We now have
- `main_binary` for running `cargo run`
- `cargo_binary` for running `cargo run --bin <name>`
- `example` for running `cargo run --example <name>`

Should `example` also be `cargo_example`?

CC @volks73 @azriel91

**Comment by epage** [comment]
Noticed this when adding a test for `Assert:example`

**Comment by volks73** [comment]
I originally had `example_binary` but that seemed redundant/confusing, so I shortened it to just `example` as I figured the usage of Cargo was implied.

The `cargo_example` works for me and is more consistent with the other function, especially given #111, where the usage of Cargo is no longer implied. The prepended "cargo" would indicate to users that the `cargo` command will be used.

**Comment by epage** [comment]
Addressed in assert_cmd
https://github.com/assert-rs/assert_cmd
