### ISSUE TITLE
Perform crates.io SEO

### ISSUE THREAD

**Issue by epage** [assert-rs/assert_cli#65]
During some usability studies, people couldn't find assert_cli.  Searching for "test command line" and "assert command line" did not return results on crates.io but "test cli" and "assert cli" did.

We should add "command" and maybe "line" tags

**Comment by killercup** [comment]
Sounds good.

(Alternatively, teach people to use CLI because "command line interface" takes too long to type! …And no, the "interface" is not optional as you are most likely not testing the command line, i.e., a terminal, with assert_cli :trollface:)

**Comment by epage** [comment]
#71  is merged, we just need to publish to see if this worked

**Comment by Dylan-DPC** [comment]
It works now: [test command line](https://crates.io/search?q=test%20command%20line), [assert command line](https://crates.io/search?q=assert%20command%20line).
