### ISSUE TITLE
Regex matching in OutputAssertionBuilder

### ISSUE THREAD

**Issue by Mike-Neto** [assert-rs/assert_cli#81]
Regular expression matching in OutputAssertionBuilder.

so something like this is posible:
```
let re = Regex::new("[0-9]{2}").unwrap();
assert_cli::Assert::command(&["echo", "42"])
    .stdout().matches(re)
    .unwrap();
```

**Comment by epage** [comment]
Agreed.

See also #20.

**Comment by Mike-Neto** [comment]
take a look at https://github.com/killercup/assert_cli/pull/85 as it has a proposed implementation for this feature.

**Comment by epage** [comment]
Copying my comment over from #85 

FYI with #98 we are switching to generic predicates. In assert-rs/predicates-rs#18 I'm adding regex to the generic predicates. It doesn't contain repetitions but I have noted that in assert-rs/predicates-rs#12 .

**Comment by epage** [comment]
Addressed in assert_cmd
https://github.com/assert-rs/assert_cmd
assert_cli is going to morph into a wider-focused tool, including things like assert_fs.  See https://github.com/assert-rs/assert_cli/issues/41
