### ISSUE TITLE
Add OutputAssertionBuilder::empty()

### ISSUE THREAD

**Issue by RazrFalcon** [assert-rs/assert_cli#82]
Currently, the only way to check that there was no output is to use `.stdout().is("")`.

I think that `.stdout().empty()` will be more elegant.

**Comment by epage** [comment]
I personally am a little unsure if the case is common enough to warrant its own check when there is a discoverable check that isn't much longer.

FYI because of #70, this will either turn into `.stdout(Output::empty)` or `.stdout(empty)`.

**Comment by epage** [comment]
Addressed in assert_cmd
https://github.com/assert-rs/assert_cmd
assert_cli is going to morph into a wider-focused tool, including things like assert_fs.  See https://github.com/assert-rs/assert_cli/issues/41
