### ISSUE TITLE
Retrieve actual stderr / stdout as string

### ISSUE THREAD

**Issue by rcoh** [assert-rs/assert_cli#94]
I'd like to do more complex validation and actually grab stdout/stderr as strings and do my own asserts on them. Is that possible? I wasn't able to find it in the docs.

**Comment by epage** [comment]
Not at the moment. In the new api design I'm working on, I'm considering it.

**Comment by rcoh** [comment]
Ideally I'd just do:
`assert_cli::Assert::main_binary().stdout().execute()` and I'd get a string.

**Comment by epage** [comment]
Addressed in assert_cmd
https://github.com/assert-rs/assert_cmd
assert_cli is going to morph into a wider-focused tool, including things like assert_fs.  See https://github.com/assert-rs/assert_cli/issues/41
